export enum ErrorCode {
  // Room errors
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  ROOM_ENDED = 'ROOM_ENDED',
  ROOM_CODE_CONFLICT = 'ROOM_CODE_CONFLICT',

  // Host secret errors
  INVALID_HOST_SECRET = 'INVALID_HOST_SECRET',
  HOST_SECRET_REQUIRED = 'HOST_SECRET_REQUIRED',

  // User errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // LiveKit errors
  LIVEKIT_TOKEN_ERROR = 'LIVEKIT_TOKEN_ERROR',

  // Rate limiting
  RATE_LIMITED = 'RATE_LIMITED',

  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
}
